services:
  admin_bot:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: admin_bot
    env_file:
      - .env
    networks:
      - shared_network
    ports:
      - "8009:8009"
    restart: unless-stopped
    

networks:
  shared_network:
    external: true