services:
  rsk_teams_app:
    build: .
    depends_on:
      rsk_teams_db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - shared_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rsk_teams_service.rule=Host(`api.rosdk.ru`) && PathPrefix(`/teams`)"
      - "traefik.http.routers.rsk_teams_service.entrypoints=websecure"
      - "traefik.http.routers.rsk_teams_service.tls.certresolver=le"
      - "traefik.http.services.rsk_teams_service.loadbalancer.server.port=8004"
  rsk_teams_db:
    image: postgres:17-alpine
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2305
      POSTGRES_DB: rsk_teams
    ports:
      - "5436:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

volumes:
  profile_postgres_data:

networks:
  shared_network:
    external: true 
