

services:
  rsk_profile_app:
    build: .
    depends_on:
      rsk_profile_db:
        condition: service_healthy
    ports:
      - "8003:8003"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - shared_network

  rsk_profile_db:
    image: postgres:17-alpine
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2305
      POSTGRES_DB: rsk_profile
    ports:
      - "5435:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

volumes:
  profile_postgres_data:

networks:
  shared_network:
    external: true 