"""fixed teams

Revision ID: 81bc94df4600
Revises: 9e2b06e3e1b4
Create Date: 2025-06-14 15:22:25.097890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bc94df4600'
down_revision: Union[str, None] = '9e2b06e3e1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
