"""Create fields for oauth2 and email fixed fixed suka blyat blyaaaat

Revision ID: 01d571ff873d
Revises: 3c48bd4b0118
Create Date: 2025-08-23 03:20:49.787555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d571ff873d'
down_revision: Union[str, None] = '3c48bd4b0118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.drop_column('users', 'mail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
