"""Create fields for oauth2 and email

Revision ID: 15f60e5d66e6
Revises: f7a17b9c7a95
Create Date: 2025-08-23 02:15:24.141442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f60e5d66e6'
down_revision: Union[str, None] = 'f7a17b9c7a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('provider_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'mail')
    # ### end Alembic commands ###
