"""Create field for verif true|false

Revision ID: a53b9936d0d9
Revises: 01d571ff873d
Create Date: 2025-08-24 06:38:52.815997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53b9936d0d9'
down_revision: Union[str, None] = '01d571ff873d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    
    
    op.execute("UPDATE users SET verified = FALSE WHERE verified IS NULL")
    
    
    op.alter_column('users', 'verified', nullable=False, server_default='false')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
