"""Create fields for test email sender

Revision ID: f0a62a3b1e9a
Revises: a53b9936d0d9
Create Date: 2025-08-24 07:06:53.339609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a62a3b1e9a'
down_revision: Union[str, None] = 'a53b9936d0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmation_token', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'users', ['confirmation_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'confirmation_token')
    # ### end Alembic commands ###
