"""test migr

Revision ID: 9b1962e215ed
Revises: ce0e59081863
Create Date: 2025-06-15 21:07:43.863201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b1962e215ed'
down_revision: Union[str, None] = 'ce0e59081863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NameIRL', sa.String(length=100), nullable=False),
    sa.Column('Surname', sa.String(length=100), nullable=False),
    sa.Column('Patronymic', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.Column('Region', sa.String(length=100), nullable=False),
    sa.Column('Type', sa.Enum('Student', 'Teacher', name='userenum'), nullable=False),
    sa.Column('Organization', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('NameIRL', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Surname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Patronymic', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('Region', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Type', postgresql.ENUM('Student', 'Teacher', name='userenum'), autoincrement=False, nullable=False),
    sa.Column('Organization', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('team', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
