"""first migration

Revision ID: ce0e59081863
Revises: 
Create Date: 2025-06-15 19:50:42.845123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0e59081863'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NameIRL', sa.String(length=100), nullable=False),
    sa.Column('Surname', sa.String(length=100), nullable=False),
    sa.Column('Patronymic', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.Column('Region', sa.String(length=100), nullable=False),
    sa.Column('Type', sa.Enum('Student', 'Teacher', name='userenum'), nullable=False),
    sa.Column('Organization', sa.String(length=100), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
