"""added columns in user_profile

Revision ID: dd269d0d4c11
Revises: 9b1962e215ed
Create Date: 2025-06-18 20:29:01.544871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd269d0d4c11'
down_revision: Union[str, None] = '9b1962e215ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('Organization_id', sa.Integer(), nullable=False))
    op.add_column('user_profile', sa.Column('team_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'team_id')
    op.drop_column('user_profile', 'Organization_id')
    # ### end Alembic commands ###
